name: Tests

on:
  - push
  - pull_request

jobs:
  lint:
    name: Lint OpenAPI
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3.3.0

      - name: Setup Node
        uses: actions/setup-node@v3.0.0
        with:
          node-version: "16"

      - name: Lint OpenAPI
        run: npx @redocly/openapi-cli lint src/openapi.yaml
